version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"       # access frontend at http://localhost:5173
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"     # access backend at http://localhost:5000
    environment:
      - FLASK_ENV=development
