services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: VITE_API_URL
        value: https://<your-backend-service-name>.onrender.com
    autoDeploy: true
    routes:
      - type: http
        source: /
        targetPort: 80

  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    routes:
      - type: http
        source: /
        targetPort: 5000
